import "../styles/globals.css"
import type { AppProps } from "next/app"
import { MoralisProvider } from "react-moralis"
import Header from "../components/Header"
import Head from "next/head"
import { NotificationProvider } from "web3uikit"

const APP_ID = process.env.NEXT_PUBLIC_APP_ID || ""
const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL || ""

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <div>
            <Head>
                <title>Smart Contract Bounty</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <MoralisProvider serverUrl={SERVER_URL} appId={APP_ID}>
                <NotificationProvider>
                    {" "}
                    <Header />
                    <Component {...pageProps} />
                </NotificationProvider>
            </MoralisProvider>
        </div>
    )
}

export default MyApp
